// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.TruthTableGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("expression")]
        public string Expression { get; set; }

        [JsonProperty("normalized")]
        public string Normalized { get; set; }

        [JsonProperty("variables")]
        public string[] Variables { get; set; }

        [JsonProperty("variableCount")]
        public long VariableCount { get; set; }

        [JsonProperty("rowCount")]
        public long RowCount { get; set; }

        [JsonProperty("rows")]
        public Row[] Rows { get; set; }

        [JsonProperty("asciiTable")]
        public string AsciiTable { get; set; }
    }

    public partial class Row
    {
        [JsonProperty("inputs")]
        public Inputs Inputs { get; set; }

        [JsonProperty("result")]
        public long Result { get; set; }
    }

    public partial class Inputs
    {
        [JsonProperty("A")]
        public long A { get; set; }

        [JsonProperty("B")]
        public long B { get; set; }

        [JsonProperty("C")]
        public long C { get; set; }

        [JsonProperty("D")]
        public long D { get; set; }

        [JsonProperty("N")]
        public long N { get; set; }

        [JsonProperty("O")]
        public long O { get; set; }

        [JsonProperty("R")]
        public long R { get; set; }
    }
}
